let num1 = prompt("Sonni kiriting 1")
let num2 = prompt("Sonni kiriting 2")
console.log(Number (num1) + Number (num2))
let num3 = prompt("Sonni kiriting 1")
let num4 = prompt("Sonni kiriting 2")
console.log(Number (num1) - Number (num2))
let num5 = prompt("Sonni kiriting 1")
let num6 = prompt("Sonni kiriting 2")
console.log(Number (num1) * Number (num2))
let num7 = prompt("Sonni kiriting 1")
let num8 = prompt("Sonni kiriting 2")
console.log(Number (num1) / Number (num2))